//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Views.DateBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Titel()
        {
            this.warehouse = new HashSet<warehouse>();
        }
    
        public int ID { get; set; }
        public string Product_Name { get; set; }
        public string Brand { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> price_per_piece { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouse> warehouse { get; set; }
    }
}
