//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Views.DateBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public int ID { get; set; }
        public int TitleID { get; set; }
        public string The_supplierID { get; set; }
        public System.DateTime Delivery_date { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual The_supplirer The_supplirer { get; set; }
        public virtual Titel Titel { get; set; }
    }
}
